site_name: Owlly — Documentation
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - python
    locale: fr
    titles_only: false
    collapse_navigation: true
pages:
    - Home : 'index.md'
    - Recrutement: 'recrut.md'
    - Commandes : 
        - 'Configuration' : 'commands/admin.md'
        - 'Fiches' : 'commands/fiches.md'
        - 'Channels' : 'commands/chan.md'
        - 'Personae' : 'commands/personae.md'
        - 'Utilitaire' : 'commands/utilitaire.md'
    - Tutoriels: 
        - 'Fiche' : 'tuto/fiche.md'
        - 'Personae' : 
            - 'Configuration' : 'tuto/persona/config.md'
            - 'Création' : 'tuto/persona/creation.md'
            - 'Message' : 'tuto/persona/message.md'
        - 'Channel' : 'tuto/chan.md'
markdown_extensions:
    - toc:
        permalink: "#"
    - footnotes
    - smarty
