site_name: Owlly — Documentation
site_description: La documentation officielle du bot de Roleplay Owlly
site_author: Owlly Team

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
        - python
    locale: fr
nav:
    - Home : index.md
    - Commandes : 
        - Configuration : commands/admin.md
        - Fiches : commands/fiches.md
        - Channels : commands/chan.md
        - Personae : commands/personae.md
        - Utilitaire : commands/utilitaire.md
    - Tutoriels: 
        - Fiche : tuto/fiches.md
        - Personae : 
            - Configuration : tuto/persona/config.md
            - Création : tuto/persona/creation.md
            - Message : tuto/persona/message.md
        - Channel : tuto/chan.md
    - Recrutement: recrut.md

markdown_extensions:
    - footnotes
    - smarty
    - admonition
    - attr_list
    - sane_lists
    - legacy_attrs
    - toc:
        permalink: "#"
        baselevel: 2
        separator: "_"
plugins:
    - ezlinks